#variables:
 # - group: db
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none 
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      show databases;
    ServerName: $(host)
    SqlUsername: $(user)
    SqlPassword: $(pass)
