variables:
  group: db
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none 
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      SELECT * 
      FROM Games;
    ServerName: '$(host1)'
    SqlUsername: '$(user)'
    SqlPassword: '$(pass)'
