pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none 

- task: AzureMysqlDeployment@1
  displayName: 'Execute Azure MySQL : InlineSqlTask'
  inputs:
    ConnectedServiceName: $(ConnectedServiceName)
    ServerName: $(ServerName)
    DatabaseName: test1-db
    SqlUsername: $(SqlUserName)
    SqlPassword: $(SqlPassword)
    TaskNameSelector: InlineSqlTask
    SqlInline: SELECT * FROM test1-db.SalesLT;
