pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none 
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      SELECT * 
      FROM Games;
    ServerName: servidores.ioseg.com
    SqlUsername: amurpo
    SqlPassword: 131fb719e5ed87c4519140c4c5e126a495306329bb4cfe3c
