pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none 
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      SELECT * 
      FROM users;
    ServerName: '$(DB_HOST)'
    DatabaseName: '$(DB_DATABASE)'
    SqlUsername: '$(DB_USERNAME)'
    SqlPassword: '$(DB_PASSWORD)'
