variables:
  group: dev
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none 
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      show databases;
    ServerName: servidores.ioseg.com
    SqlUsername: $(user)
    SqlPassword: NE2fp776KZbj@9u$Au3YSjSFLmpG!bWYfMsScho
