variables:
  - group: db1
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none 
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      show databases;
    ServerName: $(host1)
    SqlUsername: $(user)
    SqlPassword: $(pass1)
